# syntax=docker/dockerfile:1.7
#
# Lightweight production image: coming-soon / waitlist static page + nginx.
# Use when SITE_MODE=waitlist (see docker-compose.prod.yml).

FROM nginx:alpine AS runtime

RUN rm /etc/nginx/conf.d/default.conf \
 && apk add --no-cache openssl

COPY docker/nginx/40-aprly-ssl-init-prod.sh /docker-entrypoint.d/40-aprly-ssl-init.sh
RUN chmod +x /docker-entrypoint.d/40-aprly-ssl-init.sh

COPY nginx/aprly-waitlist.conf /etc/nginx/conf.d/default.conf
COPY deploy/waitlist/index.html /usr/share/nginx/html/index.html

EXPOSE 80
EXPOSE 443
