export const createPlanContent = {
  title: "Create saving plan",
  cardTitle: (n: number) => `Card #${n}`,
  removeCardAria: (n: number) => `Remove card ${n}`,
  cardNameLabel: "Card name",
  cardNamePlaceholder: "Enter your card name here",
  balanceLabel: "Balance",
  balancePlaceholder: "0",
  rateLabel: "Rate",
  ratePlaceholder: "0",
  plaidCta: "Get my cards info via Plaid",
  manualHint: "or add card info manually",
  manualAdd: "Add a card manually",
  savePlan: "Save plan",
  successTitle: "Plan created",
  successDescription: "Your cards have been analyzed. View your dashboard to start negotiating.",
  errorTitle: "Could not create plan",
  errorDescription: "Please check your card details and try again.",
} as const;
