export const planLeadDetailContent = {
  packageTitle: "Debt plan",
  cardsSection: "Cards in this plan",
  backAriaLabel: "Back to dashboard",
  selectPartner: "Select Partner",
  sendInfo: "Send info",
  sending: "Sending…",
  sendSuccessTitle: "Proposal sent",
  sendSuccessDescription: "Your hardship proposal was sent to the partner.",
  sendErrorTitle: "Could not send",
  sendErrorDescription: "Please try again.",
  status: {
    waiting: "Waiting",
    waitingDescription:
      "Your plan is ready. Choose a partner and send your hardship package to start negotiation.",
    inProgress: "In Progress",
    inProgressDescription: "Your partner is working with the issuer on your hardship request.",
    awaitingPartnerReview: "Your proposal was sent to the partner and is awaiting review.",
    won: "Won",
    denied: "Denied",
    deniedDescription: "This plan lead was closed. Return to your dashboard to review other accounts.",
  },
  metrics: {
    debt: "Debt",
    currentRate: "Current rate",
    estimatedSavings: "Est. Savings",
    targetRate: "Rate",
  },
  partnerSent: (date: string) => `The proposal was sent on ${date}.`,
  hardshipCtaSoon: "Coming soon",
  hardshipCtaSoonDescription: "This action will be available in a future release.",
  loadError: "Could not load this plan.",
  notFound: "Plan not found.",
  addCardsTitle: "Add cards to this plan",
  addCardsDescription: "New cards are added to your current plan lead — not a separate lead.",
  addCardsSave: "Save cards",
  addCardsCancel: "Cancel",
  addCardsSuccessTitle: "Cards added",
  addCardsSuccessDescription: "Your plan lead was updated.",
  addCardsErrorTitle: "Could not add cards",
  addCardsErrorDescription: "Please check your card details and try again.",
  sendRequiresPayment:
    "Pay US $39 once to unlock sending this plan to a partner. You can still edit cards before paying.",
} as const;
