export const planLeadDetailContent = {
  packageTitle: "Debt plan",
  cardsSection: "Cards in this plan",
  backAriaLabel: "Back to dashboard",
  selectPartner: "Select Partner",
  sendInfo: "Send info",
  sending: "Sending…",
  sendSuccessTitle: "Proposal sent",
  sendSuccessDescription: "Your hardship proposal was sent to the partner.",
  sendErrorTitle: "Could not send",
  sendErrorDescription: "Please try again.",
  status: {
    waiting: "Waiting",
    waitingDescription:
      "Your plan is ready. Choose a partner and send your hardship package to start negotiation.",
    inProgress: "In Progress",
    inProgressDescription: "Your partner is working with the issuer on your hardship request.",
    awaitingPartnerReview: "Your proposal was sent to the partner and is awaiting review.",
    won: "Won",
    denied: "Denied",
    deniedDescription: "This plan lead was closed. Return to your dashboard to review other accounts.",
  },
  metrics: {
    planStatus: "PLAN STATUS",
    totalPlanDebt: "TOTAL PLAN DEBT",
    initialAverageRate: "INITIAL AVERAGE RATE",
    estimatedSavings: "EST. SAVING",
    estAverageRate: "EST. AVERAGE RATE",
  },
  yourCards: "Your cards:",
  addCard: "Add card",
  cancel: "Cancel",
  deleteCardConfirmTitle: "DELETE CARD",
  deleteCardConfirmMessage:
    "Are you sure you want to delete this card? This action cannot be undone.",
  deleteCardConfirm: "CONFIRM & DELETE CARD",
  deletePlan: "Delete plan",
  deletePlanConfirmTitle: "DELETE THIS PLAN?",
  deletePlanConfirmMessage:
    "This will permanently remove the plan and its cards. This action cannot be undone.",
  deletePlanConfirm: "CONFIRM & DELETE PLAN",
  deletePlanSuccessTitle: "Plan deleted",
  deletePlanSuccessDescription: "Your plan was removed from the dashboard.",
  deletePlanErrorTitle: "Could not delete plan",
  deletePlanErrorDescription: "Please try again.",
  planActionsAriaLabel: "Plan actions",
  hardshipPortalTitle: "HARDSHIP PORTAL:",
  hardshipPortalSubtitle: "Bank Handshake — start to finish.",
  stepComplete: "Complete",
  stepInProgress: "In Progress",
  reviewBanner: (date: string) =>
    `This plan will be automatically reviewed on ${date}.`,
  partnerSent: (date: string) => `The proposal was sent on the evening of ${date}.`,
  hardshipCtaSoon: "Coming soon",
  hardshipCtaSoonDescription: "This action will be available in a future release.",
  loadError: "Could not load this plan.",
  notFound: "Plan not found.",
  addCardsTitle: "Add cards to this plan",
  addCardsDescription: "New cards are added to your current plan lead — not a separate lead.",
  addCardsSave: "Save cards",
  addCardsCancel: "Cancel",
  addCardsSuccessTitle: "Cards added",
  addCardsSuccessDescription: "Your plan lead was updated.",
  addCardsErrorTitle: "Could not add cards",
  addCardsErrorDescription: "Please check your card details and try again.",
  sendRequiresPayment:
    "Pay US $39 once to unlock sending this plan to a partner. You can still edit cards before paying.",
  partnerModal: {
    title: "SEND YOUR PLAN INFO TO THE PARTNER",
    subtitle: "Select a partner you like:",
    sendInfo: "SEND INFO",
    empty: "No partners are available yet.",
  },
  partnerNameModal: {
    title: "ADD YOUR NAME",
    subtitle: "Please enter your name before selecting a partner.",
    firstName: "First name",
    lastName: "Last name",
    continue: "SAVE TO PROCEED",
    saving: "Saving…",
    fieldRequired: "This field is required",
  },
  sendToPartnerCta: "SEND TO PARTNER",
} as const;
