import {
  LegalH2,
  LegalH3,
  LegalP,
  formatLegalInline,
} from "@/components/legal/legal-text";

export function TermsOfServiceBody() {
  return (
    <>
      <LegalP>
        Please read these Terms of Service (&quot;Terms&quot;) carefully before
        using APrly. These Terms form a binding agreement between you and APrly
        (&quot;APrly,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;)
        governing your access to and use of our website and web application located
        at aprly.ai and any related services (collectively, the &quot;Service&quot;).
        By creating an account or otherwise using the Service, you agree to be bound
        by these Terms. If you do not agree, do not use the Service.
      </LegalP>

      <LegalH2>1. ELIGIBILITY</LegalH2>
      <LegalP>
        You must be at least 18 years old and capable of forming a binding contract
        to use the Service. By using the Service, you represent that you meet these
        requirements and that you are a resident of the United States, as the
        Service is currently designed and offered for use within the United States
        only.
      </LegalP>

      <LegalH2>2. DESCRIPTION OF THE SERVICE</LegalH2>
      <LegalP>
        APrly is a web-based debt audit and optimization tool. Users may connect
        credit card accounts through our banking data partner, Plaid Inc., or enter
        card information manually, in order to receive an analysis of their debt,
        interest costs, and a plan intended to help reduce interest expense.
        Following payment of the Audit Access Fee described in Section 6, users may
        also choose to submit their information for referral to one of our business
        partners.
      </LegalP>

      <LegalH2>3. NOT FINANCIAL, LEGAL, TAX, OR CREDIT REPORTING ADVICE</LegalH2>
      <LegalP>
        The Service is provided for informational and educational purposes only. APrly
        is not a law firm, financial advisory firm, tax advisor, or credit bureau,
        and nothing provided through the Service constitutes legal, financial, or tax
        advice. Any savings estimates, interest rate comparisons, or debt plans
        generated by the Service are estimates only, based on the information you
        provide, and are not guarantees of actual results. Any credit score or
        credit-related figure displayed within the Service is illustrative/sample
        data and does not reflect your actual credit report or credit score. You
        should consult a qualified professional before making financial decisions.
        Your use of any information provided through the Service is at your own
        risk.
      </LegalP>

      <LegalH2>4. ACCOUNT REGISTRATION AND SECURITY</LegalH2>
      <LegalP>
        To use most features of the Service, you must register for an account using a
        valid email address and password. You are responsible for maintaining the
        confidentiality of your login credentials and for all activity that occurs
        under your account. You agree to notify us promptly of any unauthorized use
        of your account. We are not liable for any loss arising from your failure to
        safeguard your account credentials.
      </LegalP>

      <LegalH2>5. CONNECTING BANK ACCOUNTS THROUGH PLAID</LegalH2>
      <LegalP>
        If you choose to connect a credit card account, you will be directed to
        authenticate with your financial institution through Plaid&apos;s secure
        interface. By doing so, you authorize APrly, through Plaid, to access and
        retrieve certain account and liability information (such as balance and
        interest rate) for the purpose of generating your debt analysis. You
        represent that you are authorized to grant this access to the linked
        account(s). You may disconnect linked accounts or discontinue this feature
        at any time by using manual entry instead, or by ceasing use of the Service.
        Our use of information obtained through Plaid is described in our Privacy
        Policy.
      </LegalP>

      <LegalH2>6. FEES AND PAYMENT</LegalH2>

      <LegalH3>6.1 Audit Access Fee</LegalH3>
      <LegalP>
        Access to the full debt audit and plan features requires payment of a
        one-time Audit Access Fee of $39 USD, processed securely through our payment
        processor, Stripe.
      </LegalP>

      <LegalH3>6.2 Subscriptions</LegalH3>
      <LegalP>
        From time to time, we may offer optional subscription plans in addition to,
        or instead of, the one-time fee. If you enroll in a subscription, you
        authorize us to charge your payment method on a recurring basis at the
        interval and rate presented to you at the time of signup, until you cancel.
        You may cancel a subscription at any time through your account settings;
        cancellation will take effect at the end of the then-current billing period,
        and no partial-period refunds will be issued.
      </LegalP>

      <LegalH3>6.3 No Refunds</LegalH3>
      <LegalP>
        All payments, including the Audit Access Fee and any subscription charges,
        are non-refundable except where required by applicable law. Please review
        your order carefully before completing payment.
      </LegalP>

      <LegalH3>6.4 Payment Processing</LegalH3>
      <LegalP>
        All payment card information is collected and processed directly by Stripe.
        We do not store your full payment card number. By making a payment, you also
        agree to Stripe&apos;s terms of service, available at stripe.com/legal.
      </LegalP>

      <LegalH2>7. PARTNER REFERRALS</LegalH2>
      <LegalP>
        If, after paying the Audit Access Fee, you choose to submit your information
        for referral to a debt-relief, refinancing, or lending partner, you
        authorize APrly to share the relevant information you provided (including
        contact details and the financial information generated by your audit) with
        the partner we assign to your referral. Any resulting engagement, offer, or
        agreement between you and that partner is solely between you and the partner,
        and is governed by the partner&apos;s own terms. APrly is not a party to,
        and is not responsible for, any offer, service, or agreement made available
        by a partner.
      </LegalP>

      <LegalH2>8. ACCEPTABLE USE</LegalH2>
      <LegalP>
        You agree not to: use the Service for any unlawful purpose or in violation
        of any applicable law or regulation; provide false, inaccurate, or
        misleading information; attempt to gain unauthorized access to any account,
        system, or network related to the Service, including the administrative
        portions of the Service; interfere with, disrupt, or place undue burden on
        the Service, including by circumventing rate limits or other technical
        restrictions; reverse engineer, decompile, or attempt to extract the source
        code of the Service, except where permitted by law; or use any automated
        means to access or scrape the Service without our prior written consent. We
        reserve the right to suspend or terminate access for any user who violates
        this Section.
      </LegalP>

      <LegalH2>9. ACCOUNT TERMINATION</LegalH2>

      <LegalH3>9.1 Termination by You</LegalH3>
      <LegalP>
        You may delete your account at any time from your account settings. Upon
        deletion, any active subscription will be automatically cancelled and your
        account data will be removed as described in our Privacy Policy.
      </LegalP>

      <LegalH3>9.2 Automatic Termination for Inactivity</LegalH3>
      <LegalP>
        If your account remains inactive for an extended period, we will notify you
        by email. If you do not log in within the notice period, your account may be
        automatically deleted in accordance with our Privacy Policy.
      </LegalP>

      <LegalH3>9.3 Termination by Us</LegalH3>
      <LegalP>
        We may suspend or terminate your access to the Service at any time, with or
        without notice, if we reasonably believe you have violated these Terms,
        engaged in fraudulent or unlawful activity, or for any other reason at our
        discretion, including discontinuation of the Service.
      </LegalP>

      <LegalH2>10. INTELLECTUAL PROPERTY</LegalH2>
      <LegalP>
        The Service, including its software, design, text, graphics, logos, and
        other content (excluding information you submit), is owned by APrly or our
        licensors and is protected by intellectual property laws. We grant you a
        limited, non-exclusive, non-transferable, revocable license to access and use
        the Service for your personal, non-commercial use, subject to these Terms.
        You may not copy, modify, distribute, sell, or lease any part of the
        Service, nor reverse engineer or attempt to extract the source code, except
        as permitted by law.
      </LegalP>

      <LegalH2>11. DISCLAIMER OF WARRANTIES</LegalH2>
      <LegalP>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot;
        WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
        LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, NON-INFRINGEMENT, OR THAT THE SERVICE WILL BE UNINTERRUPTED,
        ERROR-FREE, OR SECURE. WE DO NOT WARRANT THE ACCURACY, COMPLETENESS, OR
        RELIABILITY OF ANY DEBT ANALYSIS, SAVINGS ESTIMATE, OR OTHER OUTPUT
        GENERATED BY THE SERVICE.
      </LegalP>

      <LegalH2>12. LIMITATION OF LIABILITY</LegalH2>
      <LegalP>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, APRLY AND ITS OFFICERS, EMPLOYEES,
        AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
        SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS,
        REVENUE, DATA, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE
        SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO
        THESE TERMS OR THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU
        PAID TO APRLY IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) $100 USD.
      </LegalP>
      <LegalP>
        Some jurisdictions do not allow the exclusion or limitation of certain
        damages, so some of the above limitations may not apply to you.
      </LegalP>

      <LegalH2>13. INDEMNIFICATION</LegalH2>
      <LegalP>
        You agree to indemnify and hold harmless APrly and its officers, employees,
        and service providers from any claims, damages, liabilities, and expenses
        (including reasonable attorneys&apos; fees) arising out of your use of the
        Service, your violation of these Terms, or your violation of any rights of a
        third party.
      </LegalP>

      <LegalH2>14. GOVERNING LAW AND DISPUTE RESOLUTION</LegalH2>
      <LegalP>
        These Terms are governed by the laws of the United States and the State of
        Delaware, without regard to conflict-of-laws principles, except to the
        extent preempted by federal law. Any dispute arising out of or relating to
        these Terms or the Service shall be resolved in the state or federal courts
        located in Delaware, and you consent to the personal jurisdiction of those
        courts.
      </LegalP>

      <LegalH2>15. CHANGES TO THESE TERMS</LegalH2>
      <LegalP>
        We may modify these Terms from time to time. If we make material changes, we
        will update the &quot;Last Updated&quot; date above and, where appropriate,
        notify you (such as by email or an in-app notice). Your continued use of the
        Service after a change becomes effective constitutes your acceptance of the
        revised Terms.
      </LegalP>

      <LegalH2>16. MISCELLANEOUS</LegalH2>
      <LegalP>
        If any provision of these Terms is found unenforceable, the remaining
        provisions will remain in full force and effect. Our failure to enforce any
        right or provision of these Terms will not be considered a waiver of that
        right or provision. These Terms, together with our Privacy Policy,
        constitute the entire agreement between you and APrly regarding the Service.
      </LegalP>

      <LegalH2>17. CONTACT US</LegalH2>
      <LegalP>If you have questions about these Terms, please contact us at:</LegalP>
      <p className="text-base leading-relaxed text-foreground/85">
        APrly
        <br />
        Email: {formatLegalInline("hello@aprly.ai")}
        <br />
        Support: {formatLegalInline("support@aprly.ai")}
      </p>
    </>
  );
}
